stages:
    - lint
    - test
    - sonar
    - deploy

image: node:lts-alpine

.add_bash: &add_bash
    - apk add --no-cache bash

.add_ssh: &add_ssh
    - 'which ssh-agent || (apk add --no-cache openssh-client)'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

# CI stages

lint:
    stage: lint
    before_script:
        - yarn install
    script:
        - yarn lint
    rules:
      - if: '$SKIP_STAGES != "true"'

test:
    stage: test
    before_script:
        - yarn install
    script:
        - yarn test
    coverage: '/Lines \W+: (\d+\.\d+)%.*/'
    artifacts:
      expire_in: 1 day
      paths:
        - coverage/
    rules:
      - if: '$SKIP_STAGES != "true"'

sonar:
  stage: sonar
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    GIT_DEPTH: '0'
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  rules:
    - if: '$SKIP_STAGES != "true" && $CI_COMMIT_BRANCH == "develop"'

# CD stages

qa:
    stage: deploy
    before_script:
        - *add_bash
        - *add_ssh
    environment:
        name: qa
        url: https://planner-qa.der-hahn.net
    script:
        - ENVIRONMENT_NAME=qa bash deploy/deploy.sh 
    rules:
      - if: '$SKIP_STAGES != "true" && $CI_COMMIT_BRANCH == "develop"'

prod:
    stage: deploy
    before_script:
        - *add_bash
        - *add_ssh
    environment:
        name: prod
        url: https://planner.der-hahn.net
    script:
        - ENVIRONMENT_NAME=prod bash deploy/deploy.sh
    when: manual
    rules:
      - if: '$SKIP_STAGES != "true"'

# renovate
include:
    - project: 'renovate-bot/renovate-runner'
      file: '/templates/renovate.gitlab-ci.yml'

renovate:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - if: '$CI_PIPELINE_SOURCE == "push"'
        - if: '$CI_COMMIT_BRANCH == "develop"'
