stages:
    - lint
    - test
    - sonar
    - deploy
    - renovate
    - renovate-cleanup

image: node:lts-alpine

.add_git: &add_git
    - apk add --no-cache git

.add_bash: &add_bash
    - apk add --no-cache bash

.add_ssh: &add_ssh
    - 'which ssh-agent || (apk add --no-cache openssh-client)'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

# CI stages
lint:
    stage: lint
    before_script:
        - yarn install
    script:
        - yarn lint
    allow_failure: false
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: always

test:
    stage: test
    before_script:
        - *add_git
        - yarn install
    variables:
        VITE_SUPABASE_URL: $VITE_SUPABASE_URL
        VITE_SUPABASE_ANON_KEY: $VITE_SUPABASE_ANON_KEY
    script:
        - yarn test
    coverage: '/Lines \W+: (\d+\.\d+)%.*/'
    artifacts:
        expire_in: 1 day
        paths:
            - coverage/
    needs: [lint]
    allow_failure: false
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: always

sonar:
    stage: sonar
    image:
        name: sonarsource/sonar-scanner-cli:latest
        entrypoint: ['']
    variables:
        SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
        GIT_DEPTH: '0'
    cache:
        key: '${CI_JOB_NAME}'
        paths:
            - .sonar/cache
    script:
        - sonar-scanner
    needs: [lint, test]
    allow_failure: true
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: always

# CD stages
qa:
    stage: deploy
    before_script:
        - *add_bash
        - *add_git
        - *add_ssh
    environment:
        name: qa
        url: https://planner-qa.der-hahn.net
    needs: [lint, test, sonar]
    script:
        - ENVIRONMENT_NAME=qa bash deploy/deploy.sh
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: always

prod:
    stage: deploy
    before_script:
        - *add_bash
        - *add_git
        - *add_ssh
    environment:
        name: prod
        url: https://planner.der-hahn.net
    script:
        - ENVIRONMENT_NAME=prod bash deploy/deploy.sh
    needs: [qa]
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: manual

# cleans the docker system after a renovate run
renovate-clean:
    stage: renovate-cleanup
    variables:
        REMOTE_SSH_HOST: $REMOTE_SSH_HOST
    before_script:
        - *add_bash
        - *add_ssh
    script:
        - ssh root@$REMOTE_SSH_HOST
        - ssh $REMOTE_SSH_HOST "docker system prune -af" # prune all docker images on server
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "develop"'
          when: always
        - when: never

include:
    - project: 'renovate-bot/renovate-runner'
      file: '/templates/renovate.gitlab-ci.yml'
      rules:
          - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "develop"'
    - template: Jobs/SAST.gitlab-ci.yml
      rules:
          - if: $CI_PIPELINE_SOURCE == "schedule"
            when: never
          - when: always
