stages:
    - lint
    - test
    - deploy

image: node:lts-alpine

before_script: &shh_before_script
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || (apt-get install -qq openssh-client)'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

# CI stages

lint:
    stage: lint
    before_script:
        - yarn install
    script:
        - yarn lint

test:
    stage: test
    before_script:
        - yarn install
    script:
        - yarn test

# CD stages

qa:
    stage: deploy
    before_script:
        - *shh_before_script
    environment:
        name: qa
        url: https://planner-qa.der-hahn.net
    script:
        - bash deploy/deploy.sh
    # only:
    # - develop

prod:
    stage: deploy
    before_script:
        - *shh_before_script
    environment:
        name: prod
        url: https://planner.der-hahn.net
    script:
        - bash deploy/deploy.sh
    when: manual
