#!/bin/bash

echo VITE_SUPABASE_URL=$VITE_SUPABASE_URL >> .env
echo VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY >> .env
echo VITE_PUBLIC_SITE_URL=$CI_ENVIRONMENT_URL >> .env
echo VITE_ENVIRONMENT_NAME=$CI_ENVIRONMENT_NAME >> .env
